services:
  blog:
    image: myvueblog
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./src/blog:/src
    ports:
      - 5173:5173
    environment:
      VITE_API_BASE: "http://localhost:8080"
  backend:
    image: glog
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./src/glog:/src
    ports:
      - 8080:8080
