services:
  blog:
    image: myvueblog
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./src/blog:/src
    ports:
      - 5173:5173
  backend:
    image: glog
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./src/glog:/src
    ports:
      - 80:80
      - 443:443
